# Main
DEBUG = True
SECRET_KEY = '{SECRET_KEY}'

# Database
SQLALCHEMY_DATABASE_URI = 'sqlite:///database.db'
SQLALCHEMY_COMMIT_ON_TEARDOWN = True
SQLALCHEMY_TRACK_MODIFICATIONS = True

# Mail
MAIL_SERVER = '{MAIL_SERVER}'
MAIL_PORT = 587
MAIL_USE_TLS = True
MAIL_USERNAME = '{MAIL_USERNAME}'
MAIL_PASSWORD = '{MAIL_PASSWORD}'
MAIL_DEFAULT_SENDER = MAIL_USERNAME

# Admin
FLASK_ADMIN_SWATCH = 'cerulean'

# WTF
WTF_CSRF_TIME_LIMIT = None